### ISSUE TITLE
Do NOT align PHP Docs and array

### ISSUE THREAD

**Issue by petrhejna** [BrandEmbassy/coding-standard#22]
One argument is, that its ugly. But ok, that opinioned. The main objective argument is, that **it forces changes on lines, where is NO change at all.**

Example:
![image](https://user-images.githubusercontent.com/383295/55724295-6ceb2280-5a0b-11e9-9532-ca4e330cf384.png)

**Suggestion**: disable this, and force the "normal" (one space only) oranization of PHP docs and arrays.

This allows us to use this code style across all Brand Embassy repositories with **ZERO CONFIG**.

**Comment by davidpilny** [comment]
I prefer NOT aligning, but I think it is ok to use it differently in each team.

We can discuss if it would be ok for everyone to have it as a default and possibly set align for Ostrava repo?

**Comment by ikvasnica** [comment]
I vote for no aligning - the main argument for me is the changing on lines when no change has happened.

**Comment by petrhejna** [comment]
![Screenshot_20190409-114058](https://user-images.githubusercontent.com/383295/55790459-a9c32200-5abc-11e9-97e5-32814a17c3d3.png)

![Screenshot_20190409-114103](https://user-images.githubusercontent.com/383295/55790428-9e6ff680-5abc-11e9-8411-4c877b9ccad2.png)

**Comment by petrhejna** [comment]
Našel jsem zajímavou diskuzi z doctrine projektu: https://github.com/doctrine/coding-standard/pull/107

**Comment by petrhejna** [comment]
Dohodli jsme se, že v zero config tyhle mezery dělat nebudeme a kluco v Ově si to kdyžtak přidají jako svoji specialitu.
